version: '3'

tasks:
  build-docker:
    desc: Build using Docker for all platforms (linux/amd64, linux/arm64, darwin/arm64)
    cmds:
      - mkdir -p dist
      - docker build -t progzer-builder .
      - docker create --name progzer-container progzer-builder
      - docker cp progzer-container:/app/progzer-linux-amd64 dist/
      - docker cp progzer-container:/app/progzer-linux-arm64 dist/
      - docker cp progzer-container:/app/progzer-darwin-arm64 dist/
      - docker rm progzer-container
      - chmod +x dist/progzer-linux-amd64 dist/progzer-linux-arm64 dist/progzer-darwin-arm64

  build:
    desc: Build locally for current platform only
    cmds:
      - mkdir -p dist
      - go build -o dist/progzer .

  build-linux-amd64:
    desc: Build locally for Linux AMD64
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -o dist/progzer-linux-amd64 .
      - cp dist/progzer-linux-amd64 dist/prgz-linux-amd64
      - chmod +x dist/prgz-linux-amd64
      - chmod +x dist/progzer-linux-amd64

  build-linux-arm64:
    desc: Build locally for Linux ARM64
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=arm64 go build -o dist/progzer-linux-arm64 .
      - cp dist/progzer-linux-arm64 dist/prgz-linux-arm64
      - chmod +x dist/prgz-linux-arm64
      - chmod +x dist/progzer-linux-arm64

  build-darwin-arm64:
    desc: Build locally for macOS ARM64
    cmds:
      - mkdir -p dist
      - GOOS=darwin GOARCH=arm64 go build -o dist/progzer-darwin-arm64 .
      - cp dist/progzer-darwin-arm64 dist/prgz-darwin-arm64
      - chmod +x dist/progzer-darwin-arm64
      - chmod +x dist/prgz-darwin-arm64

  build-all:
    desc: Build locally for all platforms
    deps: [build-linux-amd64, build-linux-arm64, build-darwin-arm64]

  test-e2e:
    desc: Run E2E tests
    deps: [build]
    cmds:
      - chmod +x test.sh
      - ./test.sh

  test:
    desc: Run app tests
    cmds:
      - go test -v ./...

  tests:
    desc: Run all tests
    cmds:
      - task: test
      - task: test-e2e

  clean:
    desc: Clean up
    cmds:
      - rm -rf dist
      - rm -f test_file test_file.gz
      - docker rmi progzer-builder || true
